### ISSUE TITLE
Marlin Inclusion

### ISSUE THREAD

**Issue by codexmas** [mzbotreprap/VORON#4]
Wanted to know why the Marlin codebase is included vs having config files and patches?

**Comment by mzbotreprap** [comment]
Haven't had time to clean that up. I initially pushed the whole thing in because I was making a ton of changes to support Cyclops extruder (2 extruder motors, 1 heater block) and got tired of not having revision control.

I don't really use that anymore, so a simple script to patch current Marlin is where it's at. This won't get fixed until the docs are wrapped up though.

**Comment by codexmas** [comment]
Nice, sounds great, was mostly curious

**Comment by codexmas** [comment]
Closing
