### ISSUE TITLE
G29, Level Bed, intermittently causing bed to crash into nozzles.

### ISSUE THREAD

**Issue by CarnufexG** [mzbotreprap/VORON#63]
When a G29, Level bed, g-code command is issued the 9 point bed leveling routine appears to not sense the Z probe (in the same spot every time it happens) causing the bed to crash into the nozzles. It has happened on 3 occasions and the X carriage is always in the middle right (A motor side, middle row) when the bed hits. I've stopped using G29 and the LCD panel as often. It is a very intermittent problem and cannot be produced on demand. The bot functions fine otherwise.

**Comment by dgcaste** [comment]
Do you g28 first?

Daniel


On Nov 29, 2016, at 1:14 AM, Carnufex G <notifications@github.com> wrote:

When a G29, Level bed, g-code command is issued the 9 point bed leveling routine appears to not sense the Z probe (in the same spot every time it happens) causing the bed to crash into the nozzles. It has happened on 3 occasions and the X carriage is always in the middle right (A motor side, middle row) when the bed hits. I've stopped using G29 and the LCD panel as often. It is a very intermittent problem and cannot be produced on demand. The bot functions fine otherwise.

**Comment by CarnufexG** [comment]
Yes, I always G28 before G29.

**Comment by dgcaste** [comment]
Could be an electrical connection thing there. Move the carriage to that area, get the nozzle to touch the bed so the probe is unquestionably in range, then wiggle the wire harness and see if the light flickers. 


On Nov 29, 2016, at 2:33 PM, Carnufex G <notifications@github.com> wrote:

Yes, I always G28 before G29.

**Comment by CarnufexG** [comment]
I ended up removing and repositioning the probe... was making noise anyway (resonance). Will see if it hiccups again. Thanks for the suggestions.

**Comment by CarnufexG** [comment]
Induction probe mount cracked.
